### ISSUE TITLE
Improve node_types data format

### ISSUE THREAD

**Issue by edlanglois** [causalincentives/pycid#19]
It's awkward that the parameter must be a dictionary with the keys 'D' and 'U'. That isn't very obvious of a requirement and easy to mess up. Some suggestions:

Keeping the existing structure but as a `NamedTuple`:
```python
class NodeTypes(NamedTuple):
    decisions: Sequence[str]
    utilities: Sequence[str]

# node_types maps agent => NodeTypes
def __init__(..., node_types: Dict[str, NodeTypes])
```
or as separate arguments:
```python
def __init__(...
    decisions: Dict[str, Sequence[str]],  # Mapping agent => decision nodes
    utilities: Dict[str, Sequence[str]], # Mapping agent => utility nodes
    )
```

or per-node
```python
def __init__(..., node_types: Dict[str, Tuple[str, str]]) # Mapping node => ('D'|'U', agent)
```

**Comment by RyanCarey** [comment]
Agreed! I think separate arguments is clearer / more canonical than the NamedTuple solution. 
With the per-node solution, would you expect to have to give a node type to the chance nodes (as well as decisions/utilities)? Seems kinda verbose.

**Comment by edlanglois** [comment]
No, I think for node_types we can take any missing nodes to be chance nodes. But yeah, even then it's likely to be more verbose than the others because you have to repeat the agent label a bunch of times if the agent has many decision or utility nodes.

**Comment by edlanglois** [comment]
Closed by https://github.com/causalincentives/pycid/commit/ae095d7729e2018e3b96b0026ab80d08372b08d8
