### ISSUE TITLE
Rename `state_names` => `domain`?

### ISSUE THREAD

**Issue by edlanglois** [causalincentives/pycid#28]
I find `state_names` confusing, especially since numbers are allowed. How about `domain`?

Other options could be `states` or `outcomes`. `values` would have been an option if not for pgmpy using it for the probability table (why didn't they call that `probabilities`?).

**Comment by Jamesfox1** [comment]
we could obviously redefine if we wanted to though!

**Comment by edlanglois** [comment]
Decision: Use `domain` in place of `state_names` and make it a list instead of a dict.

**Comment by RyanCarey** [comment]
Plan based on discussion in today's call:

Update "FunctionCPD" to accept "domain" as a (List-typed) argument, instead of state_names.
Update FunctionCPD.init to assign "state_names" the union of state_names of all parents, plus {self.variable_name:self.domain} from that FunctionCPD itself.

**Comment by tom4everitt** [comment]
Done. 

I also added self.state_names to MACIDBase, so that we can have a global state_names dictionary for all CPDs. Possibly this means we no longer need the workaround in MACIDBase.query, I haven't checked.
