### ISSUE TITLE
Bug in revised context workaround

### ISSUE THREAD

**Issue by edlanglois** [causalincentives/pycid#33]
For the [revised context workaround of MACIDBase.query](https://github.com/causalincentives/pycid/blob/f005aceeb7ace63796eea603a43abb6926f84475/pycid/core/macid_base.py#L201) it looks like the way pgmpy determines if you are passing indices is to [check if any are not valid state names](https://github.com/pgmpy/pgmpy/blob/e52f836769cea5ef5928eb5094670e31fb189ce2/pgmpy/factors/discrete/DiscreteFactor.py#L510). As a result, this workaround will fail if it is ever the case that state_names are the numbers 0..n but not in order. Then pgmpy will think we're passing state names when really we're passing indices.

I don't see how to get around this with pgmpy as-is. What bug is this a workaround for?

**Comment by Jamesfox1** [comment]
are you sure it fails for this....?

**Comment by Jamesfox1** [comment]
pgmpy has a bug where it doesn't handle Bayesianmodel.query when passing in state names which aren't the indices :( I've lodged an issue with them

**Comment by edlanglois** [comment]
I haven't actually tested it so I might be wrong. I noticed though that the warning pgmpy produces when it decides the state names are indicies is only produced in one test case: `test_expected_utility` when using `"d"` or `"c"` as values. So that suggests to me that it is interpreting the states as labels in all other cases.

**Comment by tom4everitt** [comment]
@Jamesfox1, could you link to the pgmpy bug that you filed for this?

It would be good to test if this actually fails. If it does, one proper workaround would be to before running a query, first create a copy of the BayesianModel, where all state_names are removed, and then run the query on that copy

**Comment by edlanglois** [comment]
I spent a bit of time earlier this week trying to diagnose the pgmpy bug. I can confirm that there is one: if you use `context` instead of `revised_context` then the test with `d` and `c` states fails. I haven't yet identified the cause though. I noticed that `pgmpy` creates a ton of copies of the CPDs during `query` and in some of those copies the state labels are gone. I'm suspicious of the operators like __mul__ possibly not preserving labels if only one side has them but haven't checked it out further.

**Comment by tom4everitt** [comment]
I [implemented](https://github.com/causalincentives/pycid/commit/490ee2f80951401d78fc4fc28b58804fa9592d03) the fix that I proposed above for this. 

Basically, make a copy of the CID that doesn't have any state_names, and run the query on that.
