### ISSUE TITLE
factor out CausalBayesianNetwork

### ISSUE THREAD

**Issue by tom4everitt** [causalincentives/pycid#46]
MACIDBase is becoming quite large, and combines two separate roles:
1. Extend BayesianModel with queries, interventions, and capability of handling StochasticFunctionCPDs
2. Handle influence diagram specific functions like different node types and computing optimal decision rules

It would probably be good to separate these functions into two different classes.

Basically, CausalBayesianNetwork would do:
* add_cpds
* Most of query (except for checking instantiating decision nodes)
* intervene
* expected_value
* draw (all nodes types would be white circles)

The rest would stay in MACIDBase, which now inherits from CausalBayesianNetwork instead of pgmpy.CausalModel

**Comment by Jamesfox1** [comment]
I'll do this now

**Comment by Jamesfox1** [comment]
done
