### ISSUE TITLE
Possible interface change: specifying a model with a dictionary

### ISSUE THREAD

**Issue by tom4everitt** [causalincentives/pycid#47]
The current add_cpds method is quite complex, and so is the way we extend TabularCPD by not calling `super.__init__` in `__init__`. There should be a better way of doing this. The following is a proposal for how.

Instead of using `add_cpds`, we could define our own method `add_model`, which takes a dictionary `{variable: function/dictionary/list}` as input. For example:
```
cid.add_model({
'S' : {-1: 0.5, 1:0.5},
'D': [-1, 1],
'U': lambda s, d: s * d
})
```

It is the responsibility of CausalBayesianNetwork to derive TabularCPDs and add them to BayesianModel, with the help of modified versions StochasticFunctionCPD etc.

Why this is better:
* The CID (and the rest of the model) will be known at the time StochasticFunctionCPD is instantiated. This means that the init method of StochasticFunctionCPD can instantiate TabularCPD, and we no longer need the two-stage initialization.
* The user needs to do less typing, and doesn't need to import or know about various CPD classes

Implementation:
* The model-dictionary can be stored as a (public) attribute model_dictionary of CausalBayesianNetwork, so that it's easy to just update a single element.
* Rather than trying to enforce that updates to CausalBayesianNetwork.model_dictionary only happen via add_model, we can instead check at query-time if any changes have happened since last time we derived TabularCPDs. To this end, we keep a copy of model_dictionary as a private attribute `CausalBayesianNetwork ._instantiated_model_dictionary`. The first thing `query()` does is that it checks whether `model_dictionary` is different from `_instantiated_model_dictionary`. If it is, `query` rederives the TabularCPDs. (In practice, there will be a method `derive_tabular_cpds` which is primarily called from `query`)
* MACIDBase adds to the abilities of CausalBayesianNetwork, by being able to derive a DecisionDomainCPD from a list of outcomes in the model_dictionary. (CausalBayesianNetwork will not be able to handle lists.)
* The neat trick of `StochasticFunctionCPD('Y', lambda x: {x: 0.9}, domain=[0, 1])` for copying x with probability 0.9, can still be achieved by `add_model({'Y': lambda x: {0: None, 1: None, x: 0.9})`, as apparently Python allows the same to be specified key several times, with the latest instance overriding.

**Comment by edlanglois** [comment]
I am thinking something like:
```
cid.add_variable('S', {-1: 0.5, 1:0.5})
...
cid.add_variable('Y',  lambda x: {x: 0.9}, domain=[0, 1])
```

**Comment by tom4everitt** [comment]
Started work on this in this branch https://github.com/causalincentives/pycid/tree/new_interface

**Comment by tom4everitt** [comment]
implemented, closing this issue
