### ISSUE TITLE
AttributeError: 'CID' object has no attribute 'is_dconnected' in Why_fairness_labels notebook

### ISSUE THREAD

**Issue by sbenthall** [causalincentives/pycid#58]
**Describe the Issue**
A clear and concise description of what the Issue is.

**Your environment**
* PyCID version/commit hash : 114e1fdcd4
* Python version : 3.9.7
* Operating System : Ubuntu

**Steps to reproduce**
In the `Why_fair_labels_may_yield_unfair_models_AAAI_22` notebook, in cell [4], I get the error:

```
AttributeError: 'CID' object has no attribute 'is_dconnected'
```

**Comment by RyanCarey** [comment]
Pgmpy renamed a method name (that we inherit) from "is_active_trail" to "is_dconnected", and we've updated accordingly. Try upgrading your pgmpy to 0.1.17 to fix the problem.

**Comment by sbenthall** [comment]
Thank you. This was indeed an environment issue. It's fixed on my end.

For what it's worth, I'm getting different results in two different environments still:

- In the development environment set up with `python3 -m pip install --editable .[test]` from a clone of `master`, it works.  `pgmpy` is version 0.1.17

- In a general Python 3 environment, `pycid` is installed by the notebook with the following code block:

```
#importing necessary libraries
try:
    import pycid
except ModuleNotFoundError:
    import sys
    !{sys.executable} -m pip install git+https://github.com/causalincentives/pycid
    import pycid
```

For some reason, in this environment `pgmpy` is installed as version `0.1.13`.

**Comment by RyanCarey** [comment]
Good!
Re the general Python3 environment, I think git calls setup.py, which calls setup.cfg, which does currently include the code `install_requires=pgmpy==0.1.17`. Not sure why it's not working. @Jamesfox1 , any ideas?

**Comment by Jamesfox1** [comment]
Thanks for identifying this @sbenthall ! I think I've now fixed this problem with the latest PyCID release. 

Namely, running the following does now install pgmpy as version 0.1.17:
`#importing necessary libraries
try:
    import pycid
except ModuleNotFoundError:
    import sys
    !{sys.executable} -m pip install git+https://github.com/causalincentives/pycid
    import pycid`
