### ISSUE TITLE
Remove linting from check-code.sh?

### ISSUE THREAD

**Issue by RyanCarey** [causalincentives/pycid#63]
When I tried to merge Sebastian Benthall's changes (https://github.com/causalincentives/pycid/pull/62) I noticed that I couldn't see the results of the actual tests, because the linting scripts (like Black) noticed errors, which halted the testing. And these linting errors weren't even in the files that Sebastian was editing, meaning that people have been committing without waiting for these tests to pass anyway. So it seems better to use a more limited set of tests - say, just the unit tests, perhaps the typechecker, but not the linting scripts - and then actually run the tests to completion before accepting a commit.

Concretely, we would comment out 

```
python3 -m flake8
echo "passed lint"
```

and maybe also
```
python3 -m mypy .
echo "passed type test"
```

**Comment by Jamesfox1** [comment]
Interesting - the linting checks should be done automatically using the pre-commit hook every time a user commits (which checks the style wrst to Black). running:
`pre-commit run --all-files`
allows one to apply this manually, and this should automatically update all of the formatting inline with Black.

That being said, maybe I've set something up to do this only my local machine. I'll have a look

**Comment by Jamesfox1** [comment]
@RyanCarey are you happy that if you run the following before committing that this should all be resolved?
```
pip3 install pre-commit
pre-commit install
```

**Comment by Jamesfox1** [comment]
All tests should now pass
