### ISSUE TITLE
Handle real-valued state_names

### ISSUE THREAD

**Issue by tom4everitt** [causalincentives/pycid#9]
These tests fail occasionally. We need to figure out why

https://github.com/causalincentives/pycid/runs/1950669614

**Comment by tom4everitt** [comment]
And sometimes tests time out. Why? Which ones?

**Comment by tom4everitt** [comment]
The reason seems to be a problem with real-valued decision_names, produced by impute_conditional_expectation_policy. Not sure how to fix. Possibly we could use the index rather than the name for queries, somehow

**Comment by tom4everitt** [comment]
I suspect this will be problem not just for decision_names, but also for other variables. We should come up with a principled solution, possibly by always running queries on indices rather than state_names (using name2no to convert).

For now I've commented out the failing tests

**Comment by Jamesfox1** [comment]
The issue was found to lie with Pgmpy. A work around has been implemented for the time being, which circumvent's the bug in our codebase.
